#!/usr/bin/env node
/*
 * PDV Integrity Harness — one re-runnable pass over every PDV integrity check,
 * aggregated into a single status + ledger (per the cross-cutting-audit-doctrine:
 * consolidate the ad-hoc tools into one suite). Each check stays the source of
 * truth for its own ledger; this is the orchestrator + roll-up.
 *
 * The houseCARL liveness probe is the ESP-reality proof layer: when it is DOWN,
 * live-ESP checks are SKIP-not-PASS (the e2e gate already enforces this internally).
 *
 * Exit 1 iff a hard GATE check fails or a check errors.
 * Findings-style checks (floor, score, specced-minus) report counts, never block.
 * Read-only except this harness's own ledger.
 *
 * Flags: --skip-slow omits the dotnet-backed e2e gate + completeness audit.
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";

const ROOT = process.cwd().replace(/\\/g, "/");
const OUT_MD = `${ROOT}/references/authoring/PDV_IntegrityHarnessLedger.md`;
const SKIP_SLOW = process.argv.includes("--skip-slow");

const CHECKS = [
  { id: "mcp_liveness", role: "proof", cmd: ["tools/pdv_mcp_check.mjs", "--json"], read: (j) => j?.ok ? "live" : "down" },
  { id: "signal_e2e_gate", role: "gate", slow: true, cmd: ["tools/pdv_signal_e2e_gate.mjs"], read: (j) => j ? `${j.counts?.GREEN ?? "?"} GREEN / ${j.counts?.RED ?? 0} RED; parity ${j.curatedSignalParity?.status ?? "?"}` : null },
  { id: "signal_floor", role: "findings", cmd: ["tools/pdv_signal_floor_audit.mjs"], read: () => "see PDV_SignalFloorLedger" },
  { id: "p2_formlist_esp", role: "findings", cmd: ["tools/pdv_p2_formlist_esp_audit.mjs", "--json"], read: (j) => j?.summary ? (j.summary.inconclusive ? `INCONCLUSIVE (bridge down: ${j.summary.inconclusiveReason ?? "?"})` : `${j.summary.populated}/${j.summary.surfaces} populated; ${j.summary.empty} empty; drift ${j.summary.driftRows}; fill-missing ${j.summary.fillMissingRows}; fails ${j.summary.fails}`) : null },
  { id: "spine_stack_score", role: "findings", cmd: ["tools/pdv_spine_stack_score.mjs"], read: (j) => j ? `worst ${j.worstFirst?.[0] ?? "?"}; ${j.parityTargets?.length ?? "?"} targets; ${j.diegeticDeadDeclarations?.length ?? 0} dead-decls` : null },
  { id: "specced_minus", role: "findings", cmd: ["tools/pdv_specced_minus_audit.mjs"], read: (j) => j ? `${j.unemitted?.length ?? "?"} unemitted minuses` : null },
  { id: "completeness", role: "findings", slow: true, cmd: ["tools/pdv_completeness_audit.mjs", "--json"], read: (j) => j ? `${j.status}; ${j.counts ? Object.entries(j.counts).map(([k, v]) => `${k}=${v}`).join(" ") : ""}` : null },
  { id: "deity_chain", role: "gate", cmd: ["tools/pdv_deity_chain_audit.mjs", "--json"], read: (j) => j ? `${j.blockers} blockers (${j.resolutionGaps} resolution / ${j.reachabilityGaps} reachability)` : null },
  { id: "eligibility_reward_coverage", role: "gate", cmd: ["tools/pdv_eligibility_reward_coverage_audit.mjs", "--json"], read: (j) => j ? `${j.rows ?? "?"} rows; ${j.failures ?? "?"} failures` : null },
];

function main() {
  const results = [];
  for (const check of CHECKS) {
    if (SKIP_SLOW && check.slow) { results.push({ ...check, status: "SKIPPED", exitCode: null, detail: "--skip-slow" }); continue; }
    const r = spawnSync(process.execPath, check.cmd, { cwd: ROOT, encoding: "utf8", timeout: 180_000, maxBuffer: 64 * 1024 * 1024, windowsHide: true });
    const json = parseJson(r.stdout);
    let detail = null;
    try { detail = check.read(json); } catch { detail = null; }
    results.push({
      ...check,
      exitCode: r.status,
      status: r.error ? "ERROR" : (check.role === "gate" ? (r.status === 0 ? "PASS" : "FAIL") : (r.status === 0 ? "OK" : "NONZERO")),
      detail: detail ?? (r.error ? String(r.error.message) : `exit ${r.status}`),
    });
  }

  const gates = results.filter((x) => x.role === "gate");
  const errored = results.filter((x) => x.status === "ERROR");
  const blocked = gates.some((g) => g.status === "FAIL") || errored.length > 0;
  const overall = blocked ? "FAIL" : "PASS";

  writeLedger(results, overall);

  console.log(JSON.stringify({
    status: overall,
    gate: gates.length ? gates.map((g) => `${g.id}: ${g.status}${g.detail ? ` (${g.detail})` : ""}`).join("; ") : "skipped",
    checks: results.map((x) => `${x.id}: ${x.status}${x.detail ? ` (${x.detail})` : ""}`),
    ledger: "references/authoring/PDV_IntegrityHarnessLedger.md",
  }, null, 2));
  process.exitCode = overall === "PASS" ? 0 : 1;
}

function parseJson(text) {
  const raw = String(text ?? "");
  const start = raw.indexOf("{");
  const end = raw.lastIndexOf("}");
  if (start < 0 || end < start) return null;
  try { return JSON.parse(raw.slice(start, end + 1)); } catch { return null; }
}

function writeLedger(results, overall) {
  const md = ["# PDV Integrity Harness Ledger", "", "GENERATED by tools/pdv_integrity_harness.mjs - do not hand-edit.", "",
    `Overall: **${overall}** (FAIL iff a gate check fails or a check errors; findings-style checks report counts and never block).`, "",
    "| Check | Role | Status | Detail |", "|---|---|---|---|"];
  for (const r of results) md.push(`| ${r.id} | ${r.role} | ${r.status} | ${asciiSafe(r.detail)} |`);
  md.push("");
  fs.writeFileSync(OUT_MD, md.join("\n") + "\n", "utf8");
}

function asciiSafe(v) { return String(v ?? "").replace(/\|/g, "/").replace(/[^\x00-\x7F]/g, "?"); }

main();
