#!/usr/bin/env node
/*
 * PDV Specced-Minus Audit — finds penalty ("minus") curated signals that a deity
 * script DEFINES and HANDLES (a ScoreCuratedSignal branch returning a negative
 * delta) but which NO code ever EMITS (no AwardCuratedSignal[Scaled] call site).
 * That is the "declared-but-never-emitted" class (e.g. Redguard
 * SIGNAL_DEATH_DUTY_ABANDONMENT) -- the inverse of the curated-signal parity check.
 *
 * Pure static source analysis; no server. Read-only except its own ledger.
 * Self-test: PDV_SPECCED_MINUS_SELFTEST=1 injects a guaranteed unemitted minus.
 */
import fs from "node:fs";

const ROOT = process.cwd().replace(/\\/g, "/");
const SOURCE_DIR = `${ROOT}/live-source/Scripts/Source`;
const MANAGER_PATH = `${SOURCE_DIR}/PDV__ManagerQuest.psc`;
const OUT_MD = `${ROOT}/references/authoring/PDV_SpeccedMinusLedger.md`;
const OUT_CSV = `${ROOT}/references/authoring/PDV_SpeccedMinusLedger.csv`;

function main() {
  if (!fs.existsSync(SOURCE_DIR)) throw new Error(`Source dir not found: ${SOURCE_DIR}`);
  const files = fs.readdirSync(SOURCE_DIR).filter((f) => /\.psc$/i.test(f));

  // 1. property name -> deity script type (e.g. PDV_Hist -> PDV_Deity_Hist), from manager decls.
  const propType = new Map();
  if (fs.existsSync(MANAGER_PATH)) {
    const managerText = fs.readFileSync(MANAGER_PATH, "utf8");
    for (const m of managerText.matchAll(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s+Property\s+(PDV_[A-Za-z0-9_]+)\s+Auto\b/gim)) {
      propType.set(m[2], m[1]);
    }
  }

  // 2. Per deity/path script: the minus signals it defines+handles (delta < 0).
  const minusSignals = []; // {script, signal, delta, file}
  const manualReview = []; // branches we could not statically resolve
  for (const file of files) {
    if (!/^PDV_(Deity|DaedricPath)_/.test(file)) continue;
    const type = file.replace(/\.psc$/i, "");
    const text = fs.readFileSync(`${SOURCE_DIR}/${file}`, "utf8");
    const deltaVals = new Map();
    for (const m of text.matchAll(/Float\s+Property\s+(DELTA_[A-Za-z0-9_]+)\s*=\s*(-?\d+(?:\.\d+)?)/g)) {
      deltaVals.set(m[1], Number(m[2]));
    }
    const score = functionBody(text, "ScoreCuratedSignal");
    if (!score) continue;
    // branch pattern: == SIGNAL_X <newline> return <token>
    for (const m of score.matchAll(/==\s*(SIGNAL_[A-Za-z0-9_]+)\s*[\r\n]+\s*return\s+([A-Za-z0-9_.\-]+)/g)) {
      const signal = m[1];
      const ret = m[2];
      let delta;
      if (deltaVals.has(ret)) delta = deltaVals.get(ret);
      else if (/^-?\d+(?:\.\d+)?$/.test(ret)) delta = Number(ret);
      else { manualReview.push({ script: type, signal, ret, file }); continue; }
      if (delta < 0) minusSignals.push({ script: type, signal, delta, file });
    }
  }

  // 3. All emit sites across the source: (deity script type, signal).
  const emitted = new Set(); // `${type}::${signal}`
  const resolveType = (prop) => {
    const declared = propType.get(prop);
    if (declared) return declared;
    return `PDV_Deity_${prop.replace(/^PDV_/, "")}`;
  };
  for (const file of files) {
    const text = fs.readFileSync(`${SOURCE_DIR}/${file}`, "utf8");
    if (!text.includes("AwardCuratedSignal")) continue;
    for (const m of text.matchAll(/\bAwardCuratedSignal(?:Scaled)?\s*\(\s*(PDV_[A-Za-z0-9_]+)\s*,\s*(PDV_[A-Za-z0-9_]+)\.(SIGNAL_[A-Za-z0-9_]+)/g)) {
      emitted.add(`${resolveType(m[2])}::${m[3]}`);
    }
  }

  if (process.env.PDV_SPECCED_MINUS_SELFTEST === "1") {
    minusSignals.push({ script: "PDV_Deity_Selftest", signal: "SIGNAL_SELFTEST_UNEMITTED", delta: -9, file: "(selftest)" });
  }

  const unemitted = minusSignals.filter((s) => !emitted.has(`${s.script}::${s.signal}`));
  const wired = minusSignals.filter((s) => emitted.has(`${s.script}::${s.signal}`));

  writeLedgers(minusSignals, unemitted, wired, manualReview);

  const summary = {
    status: unemitted.length ? "FINDINGS" : "CLEAN",
    minusSignals: minusSignals.length,
    wired: wired.length,
    unemitted: unemitted.map((s) => `${s.script}.${s.signal} (${s.delta})`),
    manualReview: manualReview.map((m) => `${m.script}.${m.signal} -> ${m.ret}`),
    selftest: process.env.PDV_SPECCED_MINUS_SELFTEST === "1"
      ? (unemitted.some((s) => s.signal === "SIGNAL_SELFTEST_UNEMITTED") ? "PASS (caught injected unemitted minus)" : "FAIL")
      : "off",
    ledger: "references/authoring/PDV_SpeccedMinusLedger.md",
  };
  console.log(JSON.stringify(summary, null, 2));
}

function functionBody(text, name) {
  const re = new RegExp(`(?:^|\\n)\\s*(?:[A-Za-z_][\\w\\[\\]]*\\s+)?Function\\s+${name}\\s*\\([^)]*\\)([\\s\\S]*?)\\n\\s*EndFunction`, "i");
  const m = text.match(re);
  return m ? m[1] : null;
}

function writeLedgers(all, unemitted, wired, manualReview) {
  const md = [];
  md.push("# PDV Specced-Minus Ledger");
  md.push("");
  md.push("GENERATED by tools/pdv_specced_minus_audit.mjs - do not hand-edit.");
  md.push("");
  md.push("A minus signal is DEFINED + HANDLED (a ScoreCuratedSignal branch returns a negative delta) but never EMITTED (no AwardCuratedSignal call site). These are specced penalties that can never fire -- the declared-but-never-emitted class (open-item #6c / gap #4).");
  md.push("");
  md.push(`Summary: ${all.length} minus signals | ${wired.length} emitted | ${unemitted.length} UNEMITTED | ${manualReview.length} manual-review`);
  md.push("");
  md.push("## Unemitted minuses");
  md.push("");
  md.push("Each is either a DEAD spec (wire an emit site so the penalty can fire) or REDUNDANT (the felt penalty is applied via a substrate metric-decay path, separate from the curated signal -> remove the dead deity-signal spec). Triage per item. Until triaged, the Spine Stack Score minus_stack dim should NOT credit these as live.");
  md.push("");
  if (!unemitted.length) md.push("- none");
  for (const s of unemitted) md.push(`- **${asciiSafe(s.script)}.${asciiSafe(s.signal)}** (delta ${s.delta}) [${asciiSafe(s.file)}]`);
  md.push("");
  md.push("## Emitted minuses (wired, for reference)");
  md.push("");
  if (!wired.length) md.push("- none");
  for (const s of wired) md.push(`- ${asciiSafe(s.script)}.${asciiSafe(s.signal)} (delta ${s.delta})`);
  if (manualReview.length) {
    md.push("");
    md.push("## Manual-review (ScoreCuratedSignal branch return not statically resolved)");
    md.push("");
    for (const m of manualReview) md.push(`- ${asciiSafe(m.script)}.${asciiSafe(m.signal)} -> ${asciiSafe(m.ret)} [${asciiSafe(m.file)}]`);
  }
  md.push("");
  fs.writeFileSync(OUT_MD, md.join("\n") + "\n", "utf8");

  const csv = ["script,signal,delta,status"];
  for (const s of unemitted) csv.push(`${csvCell(s.script)},${csvCell(s.signal)},${s.delta},UNEMITTED`);
  for (const s of wired) csv.push(`${csvCell(s.script)},${csvCell(s.signal)},${s.delta},emitted`);
  fs.writeFileSync(OUT_CSV, csv.join("\r\n") + "\r\n", "utf8");
}

function csvCell(v) { const t = asciiSafe(v); return /[",\r\n]/.test(t) ? `"${t.replace(/"/g, '""')}"` : t; }
function asciiSafe(v) { return String(v ?? "").replace(/[^\x00-\x7F]/g, "?"); }

main();
